name: ai_chat_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  gemini_dart_client:
    git:
      url: git@gitlab.com:gemini_chat_app/gemini-dart-client.git
      ref: "develop"

  dio:
  either_dart:
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
